apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      imagePullSecrets:
      - name: cloudnative
      containers:
      - name: httpserver
        image: weizhanbiao/httpserver:0.1
        ports:
        - containerPort: 8080
        # 就绪
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
        # 探活
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

        lifecycle:
          # 优雅启动
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo $(KEY1) $(KEY2)"]
          # 优雅终止
          preStop:
            exec:
              command: ["/bin/sh","-c","echo contarner stop $(KEY1) $(KEY2)"]
        resources:
          limits:
            memory: "200Mi"
            cpu: "700m"
          requests:
            memory: "100Mi"
            cpu: "400m"
        
        env:
          - name: HTTPPORT
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: httpport
          - name: LOGLEVEL
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: loglevel



